server:
  port: 8082
spring:
  datasource:
    password:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  application:
    name: PAYMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411/


