server:
    port: 8081
spring:
    datasource:
        password:
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
          enabled: true
    jpa:
        show-sql: true
    application:
         name: ORDER-SERVICE

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"
