#Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    password: aaroh#123
    url: jdbc:postgresql://localhost:5432/myDatabase
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: Login-Service
  output:
    ansi:
      enabled: ALWAYS
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations:
      - classpath:/db/migration/postgresql

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframewoek.web : ERROR
    com.javaguides : DEBUG
  pattern:
    #console: "%d %-5level %logger : %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"
    #console: "%date  %highlight(%-5level) [%12.12thread] %cyan(%-40.40logger{40}) : %msg %n"
